# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VolumeSlicer_MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_VolumeSlicer(object):
    def setupUi(self, VolumeSlicer):
        VolumeSlicer.setObjectName(_fromUtf8("VolumeSlicer"))
        VolumeSlicer.resize(1800, 800)
        self.centralwidget = QtGui.QWidget(VolumeSlicer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.hz_lyt_figures = QtGui.QHBoxLayout()
        self.hz_lyt_figures.setObjectName(_fromUtf8("hz_lyt_figures"))
        self.vt_lyt_fig1 = QtGui.QVBoxLayout()
        self.vt_lyt_fig1.setObjectName(_fromUtf8("vt_lyt_fig1"))
        self.hz_lyt_figures.addLayout(self.vt_lyt_fig1)
        self.vt_lyt_fig2 = QtGui.QVBoxLayout()
        self.vt_lyt_fig2.setObjectName(_fromUtf8("vt_lyt_fig2"))
        self.hz_lyt_figures.addLayout(self.vt_lyt_fig2)
        self.vt_lyt_fig3 = QtGui.QVBoxLayout()
        self.vt_lyt_fig3.setObjectName(_fromUtf8("vt_lyt_fig3"))
        self.hz_lyt_figures.addLayout(self.vt_lyt_fig3)
        self.verticalLayout_2.addLayout(self.hz_lyt_figures)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hz_lyt_sliders = QtGui.QHBoxLayout()
        self.hz_lyt_sliders.setObjectName(_fromUtf8("hz_lyt_sliders"))
        self.sldr_fig1 = QtGui.QVBoxLayout()
        self.sldr_fig1.setObjectName(_fromUtf8("sldr_fig1"))
        self.scrlbr_fig1 = QtGui.QScrollBar(self.centralwidget)
        self.scrlbr_fig1.setOrientation(QtCore.Qt.Horizontal)
        self.scrlbr_fig1.setInvertedAppearance(False)
        self.scrlbr_fig1.setObjectName(_fromUtf8("scrlbr_fig1"))
        self.sldr_fig1.addWidget(self.scrlbr_fig1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.horizontalLayout.addLayout(self.horizontalLayout_6)
        self.lineEdit_scrlbr1 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_scrlbr1.sizePolicy().hasHeightForWidth())
        self.lineEdit_scrlbr1.setSizePolicy(sizePolicy)
        self.lineEdit_scrlbr1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_scrlbr1.setObjectName(_fromUtf8("lineEdit_scrlbr1"))
        self.horizontalLayout.addWidget(self.lineEdit_scrlbr1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.sldr_fig1.addLayout(self.horizontalLayout)
        self.hz_lyt_sliders.addLayout(self.sldr_fig1)
        self.sldr_fig2 = QtGui.QVBoxLayout()
        self.sldr_fig2.setObjectName(_fromUtf8("sldr_fig2"))
        self.scrlbr_fig2 = QtGui.QScrollBar(self.centralwidget)
        self.scrlbr_fig2.setOrientation(QtCore.Qt.Horizontal)
        self.scrlbr_fig2.setObjectName(_fromUtf8("scrlbr_fig2"))
        self.sldr_fig2.addWidget(self.scrlbr_fig2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_8)
        self.lineEdit_scrlbr2 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_scrlbr2.sizePolicy().hasHeightForWidth())
        self.lineEdit_scrlbr2.setSizePolicy(sizePolicy)
        self.lineEdit_scrlbr2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_scrlbr2.setObjectName(_fromUtf8("lineEdit_scrlbr2"))
        self.horizontalLayout_2.addWidget(self.lineEdit_scrlbr2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.sldr_fig2.addLayout(self.horizontalLayout_2)
        self.hz_lyt_sliders.addLayout(self.sldr_fig2)
        self.sldr_fig3 = QtGui.QVBoxLayout()
        self.sldr_fig3.setObjectName(_fromUtf8("sldr_fig3"))
        self.scrlbr_fig3 = QtGui.QScrollBar(self.centralwidget)
        self.scrlbr_fig3.setOrientation(QtCore.Qt.Horizontal)
        self.scrlbr_fig3.setObjectName(_fromUtf8("scrlbr_fig3"))
        self.sldr_fig3.addWidget(self.scrlbr_fig3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_9.addWidget(self.label_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_9)
        self.lineEdit_scrlbr3 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_scrlbr3.sizePolicy().hasHeightForWidth())
        self.lineEdit_scrlbr3.setSizePolicy(sizePolicy)
        self.lineEdit_scrlbr3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_scrlbr3.setObjectName(_fromUtf8("lineEdit_scrlbr3"))
        self.horizontalLayout_3.addWidget(self.lineEdit_scrlbr3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.sldr_fig3.addLayout(self.horizontalLayout_3)
        self.hz_lyt_sliders.addLayout(self.sldr_fig3)
        self.verticalLayout.addLayout(self.hz_lyt_sliders)
        self.hz_lyt_btns = QtGui.QHBoxLayout()
        self.hz_lyt_btns.setObjectName(_fromUtf8("hz_lyt_btns"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.checkBox_lockcmap = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_lockcmap.setObjectName(_fromUtf8("checkBox_lockcmap"))
        self.horizontalLayout_5.addWidget(self.checkBox_lockcmap)
        self.hz_lyt_btns.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.hz_lyt_btns)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        VolumeSlicer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(VolumeSlicer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1800, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        VolumeSlicer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(VolumeSlicer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        VolumeSlicer.setStatusBar(self.statusbar)

        self.retranslateUi(VolumeSlicer)
        QtCore.QMetaObject.connectSlotsByName(VolumeSlicer)

    def retranslateUi(self, VolumeSlicer):
        VolumeSlicer.setWindowTitle(_translate("VolumeSlicer", "Volume Slicer", None))
        self.label.setText(_translate("VolumeSlicer", "X = ", None))
        self.label_2.setText(_translate("VolumeSlicer", "Y = ", None))
        self.label_3.setText(_translate("VolumeSlicer", "Z = ", None))
        self.checkBox_lockcmap.setText(_translate("VolumeSlicer", "Lock Colormap", None))

