# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectioncalculator.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProjectionCalculator(object):
    def setupUi(self, ProjectionCalculator):
        ProjectionCalculator.setObjectName(_fromUtf8("ProjectionCalculator"))
        ProjectionCalculator.resize(808, 482)
        self.centralwidget = QtGui.QWidget(ProjectionCalculator)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lineEdit_angleFile = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_angleFile.setObjectName(_fromUtf8("lineEdit_angleFile"))
        self.verticalLayout.addWidget(self.lineEdit_angleFile)
        self.lineEdit_outputFilename = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_outputFilename.setObjectName(_fromUtf8("lineEdit_outputFilename"))
        self.verticalLayout.addWidget(self.lineEdit_outputFilename)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btn_selectAngleFile = QtGui.QPushButton(self.centralwidget)
        self.btn_selectAngleFile.setObjectName(_fromUtf8("btn_selectAngleFile"))
        self.verticalLayout_2.addWidget(self.btn_selectAngleFile)
        self.btn_outputDirectory = QtGui.QPushButton(self.centralwidget)
        self.btn_outputDirectory.setObjectName(_fromUtf8("btn_outputDirectory"))
        self.verticalLayout_2.addWidget(self.btn_outputDirectory)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.btn_go = QtGui.QPushButton(self.centralwidget)
        self.btn_go.setObjectName(_fromUtf8("btn_go"))
        self.horizontalLayout_3.addWidget(self.btn_go)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 6, 1, 1, 5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.lineEdit_theta = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_theta.setObjectName(_fromUtf8("lineEdit_theta"))
        self.gridLayout.addWidget(self.lineEdit_theta, 1, 1, 1, 1)
        self.verticalSlider_phi = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_phi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider_phi.setMaximum(3600)
        self.verticalSlider_phi.setSingleStep(1)
        self.verticalSlider_phi.setPageStep(100)
        self.verticalSlider_phi.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_phi.setTickPosition(QtGui.QSlider.NoTicks)
        self.verticalSlider_phi.setTickInterval(1)
        self.verticalSlider_phi.setObjectName(_fromUtf8("verticalSlider_phi"))
        self.gridLayout.addWidget(self.verticalSlider_phi, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.verticalSlider_theta = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_theta.setMaximum(3600)
        self.verticalSlider_theta.setSingleStep(10)
        self.verticalSlider_theta.setPageStep(100)
        self.verticalSlider_theta.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_theta.setObjectName(_fromUtf8("verticalSlider_theta"))
        self.gridLayout.addWidget(self.verticalSlider_theta, 0, 1, 1, 1)
        self.verticalSlider_psi = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_psi.setMaximum(360)
        self.verticalSlider_psi.setSingleStep(10)
        self.verticalSlider_psi.setPageStep(100)
        self.verticalSlider_psi.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_psi.setObjectName(_fromUtf8("verticalSlider_psi"))
        self.gridLayout.addWidget(self.verticalSlider_psi, 0, 2, 1, 1)
        self.lineEdit_phi = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_phi.setObjectName(_fromUtf8("lineEdit_phi"))
        self.gridLayout.addWidget(self.lineEdit_phi, 1, 0, 1, 1)
        self.lineEdit_psi = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_psi.setObjectName(_fromUtf8("lineEdit_psi"))
        self.gridLayout.addWidget(self.lineEdit_psi, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 5, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 5, 0, 1, 6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_modelFile = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_modelFile.setObjectName(_fromUtf8("lineEdit_modelFile"))
        self.horizontalLayout.addWidget(self.lineEdit_modelFile)
        self.btn_selectModel = QtGui.QPushButton(self.centralwidget)
        self.btn_selectModel.setObjectName(_fromUtf8("btn_selectModel"))
        self.horizontalLayout.addWidget(self.btn_selectModel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.checkBox_displayFigure = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_displayFigure.setObjectName(_fromUtf8("checkBox_displayFigure"))
        self.gridLayout_2.addWidget(self.checkBox_displayFigure, 2, 1, 1, 1)
        self.btn_refresh = QtGui.QPushButton(self.centralwidget)
        self.btn_refresh.setObjectName(_fromUtf8("btn_refresh"))
        self.gridLayout_2.addWidget(self.btn_refresh, 2, 2, 1, 3)
        self.verticalLayout_figure = QtGui.QVBoxLayout()
        self.verticalLayout_figure.setObjectName(_fromUtf8("verticalLayout_figure"))
        self.gridLayout_2.addLayout(self.verticalLayout_figure, 0, 1, 1, 4)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.checkBox_displayFigure.raise_()
        self.line.raise_()
        ProjectionCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ProjectionCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ProjectionCalculator.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ProjectionCalculator)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ProjectionCalculator.setStatusBar(self.statusbar)

        self.retranslateUi(ProjectionCalculator)
        QtCore.QMetaObject.connectSlotsByName(ProjectionCalculator)
        ProjectionCalculator.setTabOrder(self.lineEdit_phi, self.lineEdit_theta)
        ProjectionCalculator.setTabOrder(self.lineEdit_theta, self.lineEdit_psi)
        ProjectionCalculator.setTabOrder(self.lineEdit_psi, self.lineEdit_modelFile)
        ProjectionCalculator.setTabOrder(self.lineEdit_modelFile, self.lineEdit_angleFile)
        ProjectionCalculator.setTabOrder(self.lineEdit_angleFile, self.lineEdit_outputFilename)
        ProjectionCalculator.setTabOrder(self.lineEdit_outputFilename, self.btn_selectModel)
        ProjectionCalculator.setTabOrder(self.btn_selectModel, self.btn_outputDirectory)
        ProjectionCalculator.setTabOrder(self.btn_outputDirectory, self.btn_go)

    def retranslateUi(self, ProjectionCalculator):
        ProjectionCalculator.setWindowTitle(_translate("ProjectionCalculator", "MainWindow", None))
        self.label_3.setText(_translate("ProjectionCalculator", "Filename Containing Angles", None))
        self.label.setText(_translate("ProjectionCalculator", "Output Base Filename", None))
        self.btn_selectAngleFile.setText(_translate("ProjectionCalculator", "Browse", None))
        self.btn_outputDirectory.setText(_translate("ProjectionCalculator", "Choose Directory", None))
        self.btn_go.setText(_translate("ProjectionCalculator", "Calculate", None))
        self.label_8.setText(_translate("ProjectionCalculator", "Psi", None))
        self.label_7.setText(_translate("ProjectionCalculator", "Theta", None))
        self.label_6.setText(_translate("ProjectionCalculator", "Phi", None))
        self.label_2.setText(_translate("ProjectionCalculator", "Model", None))
        self.btn_selectModel.setText(_translate("ProjectionCalculator", "Browse", None))
        self.checkBox_displayFigure.setText(_translate("ProjectionCalculator", "Display Figure", None))
        self.btn_refresh.setText(_translate("ProjectionCalculator", "Refresh", None))

