# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phaseretrieval.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProjectionCalculator(object):
    def setupUi(self, ProjectionCalculator):
        ProjectionCalculator.setObjectName(_fromUtf8("ProjectionCalculator"))
        ProjectionCalculator.resize(808, 515)
        self.centralwidget = QtGui.QWidget(ProjectionCalculator)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_BGlevel = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_BGlevel.setObjectName(_fromUtf8("lineEdit_BGlevel"))
        self.gridLayout.addWidget(self.lineEdit_BGlevel, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 8, 0, 2, 8)
        self.verticalLayout_figure = QtGui.QVBoxLayout()
        self.verticalLayout_figure.setObjectName(_fromUtf8("verticalLayout_figure"))
        self.gridLayout.addLayout(self.verticalLayout_figure, 0, 2, 2, 2)
        self.lineEdit_satThresh = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_satThresh.setObjectName(_fromUtf8("lineEdit_satThresh"))
        self.gridLayout.addWidget(self.lineEdit_satThresh, 4, 5, 1, 2)
        self.lbl_BGlevel = QtGui.QLabel(self.centralwidget)
        self.lbl_BGlevel.setObjectName(_fromUtf8("lbl_BGlevel"))
        self.gridLayout.addWidget(self.lbl_BGlevel, 5, 0, 1, 1)
        self.lineEdit_diffpatFile = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_diffpatFile.setObjectName(_fromUtf8("lineEdit_diffpatFile"))
        self.gridLayout.addWidget(self.lineEdit_diffpatFile, 6, 3, 1, 2)
        self.lbl_satThresh = QtGui.QLabel(self.centralwidget)
        self.lbl_satThresh.setObjectName(_fromUtf8("lbl_satThresh"))
        self.gridLayout.addWidget(self.lbl_satThresh, 5, 5, 1, 2)
        self.btn_selectDiffpat = QtGui.QPushButton(self.centralwidget)
        self.btn_selectDiffpat.setObjectName(_fromUtf8("btn_selectDiffpat"))
        self.gridLayout.addWidget(self.btn_selectDiffpat, 6, 7, 1, 1)
        self.btn_go = QtGui.QPushButton(self.centralwidget)
        self.btn_go.setObjectName(_fromUtf8("btn_go"))
        self.gridLayout.addWidget(self.btn_go, 7, 2, 1, 2)
        self.checkBox_takeSqrt = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_takeSqrt.setEnabled(True)
        self.checkBox_takeSqrt.setChecked(False)
        self.checkBox_takeSqrt.setObjectName(_fromUtf8("checkBox_takeSqrt"))
        self.gridLayout.addWidget(self.checkBox_takeSqrt, 7, 7, 1, 2)
        self.lineEdit_saveFilename = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_saveFilename.setObjectName(_fromUtf8("lineEdit_saveFilename"))
        self.gridLayout.addWidget(self.lineEdit_saveFilename, 11, 2, 1, 1)
        self.btn_refineCenter = QtGui.QPushButton(self.centralwidget)
        self.btn_refineCenter.setObjectName(_fromUtf8("btn_refineCenter"))
        self.gridLayout.addWidget(self.btn_refineCenter, 9, 6, 2, 2)
        self.btn_savePattern = QtGui.QPushButton(self.centralwidget)
        self.btn_savePattern.setObjectName(_fromUtf8("btn_savePattern"))
        self.gridLayout.addWidget(self.btn_savePattern, 11, 0, 1, 1)
        self.lineEdit_BGfilename = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_BGfilename.setObjectName(_fromUtf8("lineEdit_BGfilename"))
        self.gridLayout.addWidget(self.lineEdit_BGfilename, 11, 7, 1, 2)
        self.lbl_BGfilename = QtGui.QLabel(self.centralwidget)
        self.lbl_BGfilename.setObjectName(_fromUtf8("lbl_BGfilename"))
        self.gridLayout.addWidget(self.lbl_BGfilename, 11, 4, 1, 2)
        self.btn_BGfilename = QtGui.QPushButton(self.centralwidget)
        self.btn_BGfilename.setObjectName(_fromUtf8("btn_BGfilename"))
        self.gridLayout.addWidget(self.btn_BGfilename, 11, 6, 1, 1)
        self.lbl_diffpat = QtGui.QLabel(self.centralwidget)
        self.lbl_diffpat.setObjectName(_fromUtf8("lbl_diffpat"))
        self.gridLayout.addWidget(self.lbl_diffpat, 6, 0, 1, 3)
        self.slder_contrastLow = QtGui.QSlider(self.centralwidget)
        self.slder_contrastLow.setOrientation(QtCore.Qt.Vertical)
        self.slder_contrastLow.setObjectName(_fromUtf8("slder_contrastLow"))
        self.gridLayout.addWidget(self.slder_contrastLow, 0, 0, 1, 1)
        self.verticalSlider_BGlevel = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_BGlevel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider_BGlevel.setMaximum(3600)
        self.verticalSlider_BGlevel.setSingleStep(1)
        self.verticalSlider_BGlevel.setPageStep(100)
        self.verticalSlider_BGlevel.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_BGlevel.setTickPosition(QtGui.QSlider.NoTicks)
        self.verticalSlider_BGlevel.setTickInterval(1)
        self.verticalSlider_BGlevel.setObjectName(_fromUtf8("verticalSlider_BGlevel"))
        self.gridLayout.addWidget(self.verticalSlider_BGlevel, 0, 7, 4, 1)
        self.slder_contrastHigh = QtGui.QSlider(self.centralwidget)
        self.slder_contrastHigh.setOrientation(QtCore.Qt.Vertical)
        self.slder_contrastHigh.setObjectName(_fromUtf8("slder_contrastHigh"))
        self.gridLayout.addWidget(self.slder_contrastHigh, 1, 0, 1, 1)
        self.verticalSlider_satThresh = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_satThresh.setMaximum(3600)
        self.verticalSlider_satThresh.setSingleStep(10)
        self.verticalSlider_satThresh.setPageStep(100)
        self.verticalSlider_satThresh.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_satThresh.setObjectName(_fromUtf8("verticalSlider_satThresh"))
        self.gridLayout.addWidget(self.verticalSlider_satThresh, 0, 8, 4, 1)
        self.lineEdit_contrastHigh = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_contrastHigh.setObjectName(_fromUtf8("lineEdit_contrastHigh"))
        self.gridLayout.addWidget(self.lineEdit_contrastHigh, 1, 1, 1, 1)
        self.lineEdit_contrastLow = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_contrastLow.setEnabled(True)
        self.lineEdit_contrastLow.setObjectName(_fromUtf8("lineEdit_contrastLow"))
        self.gridLayout.addWidget(self.lineEdit_contrastLow, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        ProjectionCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ProjectionCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ProjectionCalculator.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ProjectionCalculator)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ProjectionCalculator.setStatusBar(self.statusbar)

        self.retranslateUi(ProjectionCalculator)
        QtCore.QMetaObject.connectSlotsByName(ProjectionCalculator)
        ProjectionCalculator.setTabOrder(self.lineEdit_BGlevel, self.lineEdit_satThresh)
        ProjectionCalculator.setTabOrder(self.lineEdit_satThresh, self.lineEdit_diffpatFile)
        ProjectionCalculator.setTabOrder(self.lineEdit_diffpatFile, self.btn_selectDiffpat)
        ProjectionCalculator.setTabOrder(self.btn_selectDiffpat, self.btn_go)

    def retranslateUi(self, ProjectionCalculator):
        ProjectionCalculator.setWindowTitle(_translate("ProjectionCalculator", "MainWindow", None))
        self.lbl_BGlevel.setText(_translate("ProjectionCalculator", "BG Level", None))
        self.lbl_satThresh.setText(_translate("ProjectionCalculator", "Saturation Threshold", None))
        self.btn_selectDiffpat.setText(_translate("ProjectionCalculator", "Browse", None))
        self.btn_go.setText(_translate("ProjectionCalculator", "Launch Reconstruction", None))
        self.checkBox_takeSqrt.setText(_translate("ProjectionCalculator", "Take Square Root", None))
        self.btn_refineCenter.setText(_translate("ProjectionCalculator", "Optimize Center", None))
        self.btn_savePattern.setText(_translate("ProjectionCalculator", "Save Pattern", None))
        self.lbl_BGfilename.setText(_translate("ProjectionCalculator", "BG Filename", None))
        self.btn_BGfilename.setText(_translate("ProjectionCalculator", "Browse", None))
        self.lbl_diffpat.setText(_translate("ProjectionCalculator", "Diffraction Pattern Filename", None))

