# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phaseretrieval.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PhaseRetrieval(object):
    def setupUi(self, PhaseRetrieval):
        PhaseRetrieval.setObjectName(_fromUtf8("PhaseRetrieval"))
        PhaseRetrieval.resize(808, 515)
        self.centralwidget = QtGui.QWidget(PhaseRetrieval)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_figure = QtGui.QVBoxLayout()
        self.verticalLayout_figure.setObjectName(_fromUtf8("verticalLayout_figure"))
        self.horizontalLayout_16.addLayout(self.verticalLayout_figure)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.slder_BGscale = QtGui.QSlider(self.centralwidget)
        self.slder_BGscale.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slder_BGscale.setMaximum(3600)
        self.slder_BGscale.setSingleStep(1)
        self.slder_BGscale.setPageStep(100)
        self.slder_BGscale.setOrientation(QtCore.Qt.Vertical)
        self.slder_BGscale.setTickPosition(QtGui.QSlider.NoTicks)
        self.slder_BGscale.setTickInterval(1)
        self.slder_BGscale.setObjectName(_fromUtf8("slder_BGscale"))
        self.horizontalLayout_12.addWidget(self.slder_BGscale)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.lineEdit_BGscale = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_BGscale.setObjectName(_fromUtf8("lineEdit_BGscale"))
        self.horizontalLayout_14.addWidget(self.lineEdit_BGscale)
        self.lbl_BGlevel = QtGui.QLabel(self.centralwidget)
        self.lbl_BGlevel.setObjectName(_fromUtf8("lbl_BGlevel"))
        self.horizontalLayout_14.addWidget(self.lbl_BGlevel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.slder_satThresh = QtGui.QSlider(self.centralwidget)
        self.slder_satThresh.setMaximum(3600)
        self.slder_satThresh.setSingleStep(10)
        self.slder_satThresh.setPageStep(100)
        self.slder_satThresh.setOrientation(QtCore.Qt.Vertical)
        self.slder_satThresh.setObjectName(_fromUtf8("slder_satThresh"))
        self.horizontalLayout_6.addWidget(self.slder_satThresh)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lbl_satThresh = QtGui.QLabel(self.centralwidget)
        self.lbl_satThresh.setObjectName(_fromUtf8("lbl_satThresh"))
        self.horizontalLayout_10.addWidget(self.lbl_satThresh)
        self.lineEdit_satThresh = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_satThresh.setObjectName(_fromUtf8("lineEdit_satThresh"))
        self.horizontalLayout_10.addWidget(self.lineEdit_satThresh)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.slder_contrastLow = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slder_contrastLow.sizePolicy().hasHeightForWidth())
        self.slder_contrastLow.setSizePolicy(sizePolicy)
        self.slder_contrastLow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slder_contrastLow.setOrientation(QtCore.Qt.Vertical)
        self.slder_contrastLow.setObjectName(_fromUtf8("slder_contrastLow"))
        self.horizontalLayout.addWidget(self.slder_contrastLow)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_contrastLow = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_contrastLow.setEnabled(True)
        self.lineEdit_contrastLow.setObjectName(_fromUtf8("lineEdit_contrastLow"))
        self.horizontalLayout_2.addWidget(self.lineEdit_contrastLow)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.slder_contrastHigh = QtGui.QSlider(self.centralwidget)
        self.slder_contrastHigh.setOrientation(QtCore.Qt.Vertical)
        self.slder_contrastHigh.setObjectName(_fromUtf8("slder_contrastHigh"))
        self.horizontalLayout_3.addWidget(self.slder_contrastHigh)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_contrastHigh = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_contrastHigh.setObjectName(_fromUtf8("lineEdit_contrastHigh"))
        self.horizontalLayout_4.addWidget(self.lineEdit_contrastHigh)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.lbl_diffpat = QtGui.QLabel(self.centralwidget)
        self.lbl_diffpat.setWordWrap(True)
        self.lbl_diffpat.setObjectName(_fromUtf8("lbl_diffpat"))
        self.horizontalLayout_13.addWidget(self.lbl_diffpat)
        self.lineEdit_diffpatFile = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_diffpatFile.sizePolicy().hasHeightForWidth())
        self.lineEdit_diffpatFile.setSizePolicy(sizePolicy)
        self.lineEdit_diffpatFile.setObjectName(_fromUtf8("lineEdit_diffpatFile"))
        self.horizontalLayout_13.addWidget(self.lineEdit_diffpatFile)
        self.btn_selectDiffpat = QtGui.QPushButton(self.centralwidget)
        self.btn_selectDiffpat.setObjectName(_fromUtf8("btn_selectDiffpat"))
        self.horizontalLayout_13.addWidget(self.btn_selectDiffpat)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lbl_BGfilename = QtGui.QLabel(self.centralwidget)
        self.lbl_BGfilename.setWordWrap(True)
        self.lbl_BGfilename.setObjectName(_fromUtf8("lbl_BGfilename"))
        self.horizontalLayout_7.addWidget(self.lbl_BGfilename)
        self.lineEdit_BGfilename = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_BGfilename.sizePolicy().hasHeightForWidth())
        self.lineEdit_BGfilename.setSizePolicy(sizePolicy)
        self.lineEdit_BGfilename.setObjectName(_fromUtf8("lineEdit_BGfilename"))
        self.horizontalLayout_7.addWidget(self.lineEdit_BGfilename)
        self.btn_BGfilename = QtGui.QPushButton(self.centralwidget)
        self.btn_BGfilename.setObjectName(_fromUtf8("btn_BGfilename"))
        self.horizontalLayout_7.addWidget(self.btn_BGfilename)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.btn_refineCenter = QtGui.QPushButton(self.centralwidget)
        self.btn_refineCenter.setObjectName(_fromUtf8("btn_refineCenter"))
        self.verticalLayout_9.addWidget(self.btn_refineCenter)
        self.checkBox_takeSqrt = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_takeSqrt.setEnabled(True)
        self.checkBox_takeSqrt.setChecked(False)
        self.checkBox_takeSqrt.setObjectName(_fromUtf8("checkBox_takeSqrt"))
        self.verticalLayout_9.addWidget(self.checkBox_takeSqrt)
        self.horizontalLayout_15.addLayout(self.verticalLayout_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_11.addWidget(self.label_3)
        self.lineEdit_saveFilename = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_saveFilename.sizePolicy().hasHeightForWidth())
        self.lineEdit_saveFilename.setSizePolicy(sizePolicy)
        self.lineEdit_saveFilename.setObjectName(_fromUtf8("lineEdit_saveFilename"))
        self.horizontalLayout_11.addWidget(self.lineEdit_saveFilename)
        self.btn_savePattern = QtGui.QPushButton(self.centralwidget)
        self.btn_savePattern.setObjectName(_fromUtf8("btn_savePattern"))
        self.horizontalLayout_11.addWidget(self.btn_savePattern)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_11.addWidget(self.line)
        self.btn_go = QtGui.QPushButton(self.centralwidget)
        self.btn_go.setObjectName(_fromUtf8("btn_go"))
        self.horizontalLayout_11.addWidget(self.btn_go)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_11.addLayout(self.verticalLayout_7)
        self.horizontalLayout_17.addLayout(self.verticalLayout_11)
        PhaseRetrieval.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PhaseRetrieval)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        PhaseRetrieval.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PhaseRetrieval)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PhaseRetrieval.setStatusBar(self.statusbar)

        self.retranslateUi(PhaseRetrieval)
        QtCore.QMetaObject.connectSlotsByName(PhaseRetrieval)

    def retranslateUi(self, PhaseRetrieval):
        PhaseRetrieval.setWindowTitle(_translate("PhaseRetrieval", "MainWindow", None))
        self.lbl_BGlevel.setText(_translate("PhaseRetrieval", "BG Scale (%)", None))
        self.lbl_satThresh.setText(_translate("PhaseRetrieval", "Saturation Threshold", None))
        self.label.setText(_translate("PhaseRetrieval", "TextLabel", None))
        self.label_2.setText(_translate("PhaseRetrieval", "TextLabel", None))
        self.lbl_diffpat.setText(_translate("PhaseRetrieval", "Diffraction Pattern Filename", None))
        self.btn_selectDiffpat.setText(_translate("PhaseRetrieval", "Browse", None))
        self.lbl_BGfilename.setText(_translate("PhaseRetrieval", "BG Filename", None))
        self.btn_BGfilename.setText(_translate("PhaseRetrieval", "Browse", None))
        self.btn_refineCenter.setText(_translate("PhaseRetrieval", "Optimize Center", None))
        self.checkBox_takeSqrt.setText(_translate("PhaseRetrieval", "Take Square Root", None))
        self.label_3.setText(_translate("PhaseRetrieval", "TextLabel", None))
        self.btn_savePattern.setText(_translate("PhaseRetrieval", "Save Pattern", None))
        self.btn_go.setText(_translate("PhaseRetrieval", "Launch Reconstruction", None))

